'use strict';

import Macro from './macro/macro.js';
import { _COLORS_, _TYPES_ } from './utils/constants.js';

let vp = new Macro();

let root = vp.newCard(10, 845);
let rootCard, field, card;

let startField = root.addField('INICIAR', _TYPES_.LIST);
    startField.setColor(_COLORS_.RED);

    rootCard = vp.newCard(340, 19, startField);
    field = rootCard.addField('CONTROLE');
    field = rootCard.addField('CDE M2 V43', _TYPES_.LIST);
        card = vp.newCard(741, 36, field);
        card.addField('INICIAR');
        card.addField('CANCELAR');
        //vp.connect(field, card);
    field = rootCard.addField('CD CENTRO RESUL', _TYPES_.LIST);
        card = vp.newCard(740, 176, field);
        card.addField('COLETA DOMICILIAR');
        card.addField('COLETA DIVERSOS');
        card.addField('COLETA SELECTIVA');
        //vp.connect(field, card);
    field = rootCard.addField('CD UT');
    field = rootCard.addField('CD SETOR');
    field = rootCard.addField('KM INICIAL');
//vp.connect(startField, rootCard);

let driverField = root.addField('MOTORISTA', _TYPES_.LIST);
    driverField.setColor(_COLORS_.BLACK);
    rootCard = vp.newCard(531, 437, driverField);
    field = rootCard.addField('CÓDIGO MOTORISTA');
//vp.connect(driverField, rootCard);

let inspectField = root.addField('VISTORIA DIÁRIA', _TYPES_.LIST);
    inspectField.setColor(_COLORS_.PURPLE);
    rootCard = vp.newCard(1304, 43, inspectField);
        field = rootCard.addField('COMBUSTÍVEL', _TYPES_.LIST);
            card = vp.newCard(2197, 7, field);
            card.addField('COMPLETO');
            card.addField('MEIO TANQUE');
            card.addField('1/4 de TANQUE');
            card.addField('RESERVA');
            card.addField('VAZIO');
            //vp.connect(field, card); 
        field = rootCard.addField('DIFERENCIAL', _TYPES_.LIST);
            card = vp.newCard(2197, 206, field);
            card.addField('OK');
            card.addField('FAZENDO BARULHO');
            card.addField('VAZAMENTO DE ÓLEO');
            //vp.connect(field, card); 
        field = rootCard.addField('CAIXA DE CÂMBIO', _TYPES_.LIST);
            card = vp.newCard(2197, 344, field);
            card.addField('OK');
            card.addField('FAZENDO BARULHO');
            card.addField('ESCAPANDO MARCHA');
            card.addField('NAO ENTRA MARCHA');
            card.addField('VAZAMENTO');
            //vp.connect(field, card);
        field = rootCard.addField('ÓLEO DO MOTOR', _TYPES_.LIST);
            card = vp.newCard(2197, 545, field);
            card.addField('OK');
            card.addField('NÍVEL BAIXO');
            //vp.connect(field, card);
        field = rootCard.addField('ÓLEO HIDRÁULICO', _TYPES_.LIST);
            card = vp.newCard(2197, 653, field);
            card.addField('OK');
            card.addField('NÍVEL BAIXO');
            //vp.connect(field, card);
        field = rootCard.addField('GRAXA SAPATAS', _TYPES_.LIST);
            card = vp.newCard(2197, 759, field);
            card.addField('ENGRAXADO');
            card.addField('RUIM');
            //vp.connect(field, card);
        field = rootCard.addField('CAMERA DE RÉ', _TYPES_.LIST);
            card = vp.newCard(2197, 866, field);
            card.addField('FUNCIONANDO');
            card.addField('COM PROBLEMAS');
            //vp.connect(field, card);
        field = rootCard.addField('ÁGUA DO RADIADOR', _TYPES_.LIST);
            card = vp.newCard(2197, 976, field);
            card.addField('OK');
            card.addField('NÍVEL BAIXO');
            card.addField('VAZAMENTO');
            //vp.connect(field, card);
        field = rootCard.addField('FARÓIS E LANTERNAS', _TYPES_.LIST);
            card = vp.newCard(2197, 1114, field);
            card.addField('FUNCIONANDO');
            card.addField('COM PROBLEMAS');
            //vp.connect(field, card);
        field = rootCard.addField('PRESSÃO PNEU', _TYPES_.LIST);
            card = vp.newCard(2197, 1221, field);
            card.addField('OK');
            card.addField('IRREGULAR');
            //vp.connect(field, card);
        field = rootCard.addField('MOLAS', _TYPES_.LIST);
            card = vp.newCard(2197, 1332, field);
            card.addField('OK');
            card.addField('COM PROBLEMAS');
            //vp.connect(field, card);
        field = rootCard.addField('EXTINTOR', _TYPES_.LIST);
            card = vp.newCard(2197, 1441, field);
            card.addField('OK');
            card.addField('VENCIDO');
            card.addField('VAZIO');
            card.addField('SEM LACRE');
            //vp.connect(field, card);
        field = rootCard.addField('DOCUMENTOS DO VEÍCULO', _TYPES_.LIST);
            card = vp.newCard(2197, 1609, field);
            card.addField('OK');
            card.addField('VENCIDO');
            card.addField('NÃO ENCONTRADO');
            //vp.connect(field, card);
        field = rootCard.addField('TEMPERATURA DO MOTOR', _TYPES_.LIST);
            card = vp.newCard(2197, 1750, field);
            card.addField('OK');
            card.addField('ESQUENTANDO');
            //vp.connect(field, card);
    //vp.connect(inspectField, rootCard);

let workField = root.addField('EM TRABALHO', _TYPES_.LIST);
    workField.setColor(_COLORS_.INDIGO);
    
    rootCard = vp.newCard(876, 620, workField);
    field = rootCard.addField('INÍCIO COLETA');
    field = rootCard.addField('FIM COLETA');
    field = rootCard.addField('TRÂNSITO PARA DESCARGA');
    field = rootCard.addField('INÍCIO DESCARGA');
    field = rootCard.addField('FIM DESCARGA', _TYPES_.LIST);
        card = vp.newCard(1284, 618, field);
        card.addField('NR TICKET');
        card.addField('PESO KG');
        //vp.connect(field, card); 
    field = rootCard.addField('TRÂNSITO LOCAL');
    field = rootCard.addField('INÍCIO ABASTECIMENTO');
    field = rootCard.addField('FIM ABASTECIMENTO', _TYPES_.LIST);
        card = vp.newCard(1284, 740, field);
        card.addField('QTDE LITROS');
        //vp.connect(field, card); 
    field = rootCard.addField('COND LOCAIS');
    field = rootCard.addField('INÍCIO REFEIÇÃO', _TYPES_.LIST);
        card = vp.newCard(1284, 838, field);
        card.addField('CÓDIGO PONTO MOTORISTA');
        card.addField('CÓDIGO PONTO COLETOR 1');
        card.addField('CÓDIGO PONTO COLETOR 2');
        card.addField('CÓDIGO PONTO COLETOR 3');
        card.addField('CÓDIGO PONTO COLETOR 4');
        //vp.connect(field, card); 
    field = rootCard.addField('FIM REFEIÇÃO', _TYPES_.LIST);
        card = vp.newCard(1284, 1046, field);
        card.addField('CÓDIGO PONTO MOTORISTA');
        card.addField('CÓDIGO PONTO COLETOR 1');
        card.addField('CÓDIGO PONTO COLETOR 2');
        card.addField('CÓDIGO PONTO COLETOR 3');
        card.addField('CÓDIGO PONTO COLETOR 4');
        //vp.connect(field, card); 
    field = rootCard.addField('CAFÉ');
    field = rootCard.addField('A DISPOSIÇÃO');
    field = rootCard.addField('PEDIDO DE SOS');
    field = rootCard.addField('INÍCIO SOS');
    field = rootCard.addField('FIM SOS');
    field = rootCard.addField('FISCALIZAÇÃO', _TYPES_.LIST);
        card = vp.newCard(1284, 1250, field);
        card.addField('CÓDIGO FISCAL');
        card.addField('OBSERVAÇÕES');
        //vp.connect(field, card); 
    field = rootCard.addField('OBSERVAÇÕES');
    field = rootCard.addField('TROCA MOTORISTA');
    field = rootCard.addField('SAIR TRABALHO');
    field = rootCard.addField('VERIFICA COLETA');
//vp.connect(workField, rootCard); 


let changeField = root.addField('TROCA MOTORISTA', _TYPES_.LIST);
    changeField.setColor(_COLORS_.TEAL);
    rootCard = vp.newCard(530, 1122, changeField);
    field = rootCard.addField('SENHA MOTORISTA');
//vp.connect(changeField, changeCard);

let maintenanceField = root.addField('EM MANUTENÇÃO', _TYPES_.LIST);
    maintenanceField.setColor(_COLORS_.GREEN);
    rootCard = vp.newCard(523, 1274, maintenanceField);
    field = rootCard.addField('MANUTENÇÃO DENTRO DO TURNO');
    field = rootCard.addField('TROCA DE PNEUS');
    field = rootCard.addField('LAVAGEM');
    field = rootCard.addField('MANUTENÇÃO FORA DO TURNO');
    field = rootCard.addField('TROCA DE ÓLEO');
    field = rootCard.addField('SAIR MANUTENÇÃO');
//vp.connect(maintenanceField, maintenanceCard);

let startworkField = root.addField('PONTO ELETRÔNICO', _TYPES_.LIST);
    startworkField.setColor(_COLORS_.ORANGE);
    rootCard = vp.newCard(522, 1593, startworkField);
    field = rootCard.addField('ENTRADA TRABALHO', _TYPES_.LIST);
        card = vp.newCard(888, 1499, field);
        card.addField('CÓDIGO COLABORADOR');
    field = rootCard.addField('SAÍDA INTERVALO', _TYPES_.LIST);
        card = vp.newCard(888, 1578, field);
        card.addField('CÓDIGO COLABORADOR');
    field = rootCard.addField('RETORNO INTERVALO', _TYPES_.LIST);
        card = vp.newCard(888, 1654, field);
        card.addField('CÓDIGO COLABORADOR');
    field = rootCard.addField('SAÍDA TRABALHO', _TYPES_.LIST);
        card = vp.newCard(888, 1730, field);
        card.addField('CÓDIGO COLABORADOR');
    field = rootCard.addField('SAIR PONTO', _TYPES_.LIST);
        card = vp.newCard(888, 1806, field);
        card.addField('CÓDIGO COLABORADOR');    
//vp.connect(startworkField, startworkCard);

let endField = root.addField('FINALIZAR CDE', _TYPES_.LIST);
    endField.setColor(_COLORS_.BROWN);
    rootCard = vp.newCard(357, 1918, endField);
    field = rootCard.addField('SIM', _TYPES_.LIST);
        card = vp.newCard(720, 2008, field);
        card.addField('ODÔMETRO FINAL');
        card.addField('HORÍMETRO FINAL');
    field = rootCard.addField('NÃO');
//vp.connect(endField, endCard);

//new Promise(vp.redraw)
vp.redraw();
